name: Publish go binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Build Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, openbsd, netbsd, freebsd]
        goarch: ["amd64", "arm", "arm64"]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.42
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        sha256sum: true
        md5sum: false
